// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorWebAppProject.Repository.Data;

namespace RazorWebAppProject.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210827155924_SP_DeleteRecord")]
    partial class SP_DeleteRecord
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RazorWebAppProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dept")
                        .HasColumnName("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Gender")
                        .HasColumnName("Sex")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnName("Photo")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("tblEmployee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Dept = 1,
                            Email = "tuse@iamtuse.com",
                            FirstName = "tuse",
                            Gender = 1,
                            LastName = "theProgrammer"
                        },
                        new
                        {
                            Id = 2,
                            Dept = 5,
                            Email = "wonkulahp@iamtuse.com",
                            FirstName = "Precious",
                            Gender = 2,
                            Image = "focus.jpg",
                            LastName = "Wonkulah"
                        },
                        new
                        {
                            Id = 3,
                            Dept = 2,
                            Email = "test@iamtuse.com",
                            FirstName = "Test",
                            Gender = 3,
                            LastName = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
